version: '3.7'
services: 
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - 8888:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
      - mysql
    networks: 
      - myDeveloper
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: mydeveloper
      MYSQL_USER: haefrain
      MYSQL_PASSWORD: My14220309.
      MYSQL_ROOT_PASSWORD: root.14220309.*
    ports:
      - 33069:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks: 
      - myDeveloper
  php: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes: 
      - ./src:/var/www/html
    ports: 
      - 9000:80
    networks:
      - myDeveloper
networks: 
  myDeveloper: